### ISSUE TITLE
[feature request] support hatch display？

### ISSUE THREAD

**Issue by llcat** [dxfom/explorer#2]
thanks for your great job, do you have plan to support hatch display？
like predefined in autocad or self defined hatch

**Comment by luncheon** [comment]
There are many missing features. I'll try to implement them little by little when I have time.
Now that I've seen your request, I'll try the hatch feature next. But I don't know when I will, sorry.

**Comment by llcat** [comment]
thanks for your reply, this explorer is very good, hope it will become more strong
